## 期约

### 期约的状态

Promise 有三个状态：

* 待定（pending） 
* 兑现（fulfilled，有时候也称为“解决”，resolved）
* 拒绝（rejected）

默认处于 peding 装，状态一旦落定则是不可改变的。同时，也不能保证 Promise 或脱离 pending 状态。

Promise 在被创建时就会立即执行传入的参数函数。当去落定了一个 Promise 的状态后，并尝试 `await` 它，Promise 便会将其异步操作添加到当前任务队列后的微任务中。也就是下个宏任务之前。

```js
const p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    console.log(2);
    resolve();
  }, 200);
});
const p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    console.log(1);
    resolve();
  }, 100);
});
await p1;
await p2;
setTimeout(console.log, 0, "3");
// 1
// 2
// 3
```

这里在创建 Promise 时就立即执行了参数，也就是执行了 `setTimeout` 函数。抛开 Promise 不看的话，按照以往的逻辑则是 0ms 后打印 3 的任务先被送入任务队列，随后 100ms 后 p2 先被送入任务队列，最后 200ms 后 p2 被送入任务队列。

也就是 `3 1 2` 的顺序执行。但是如果我们落定了 Promise 的状态，并在最后一个 `setTimeout` 之前尝试 `await` 它，那就意味着这两个 Promise 会被送入当前任务队列后的微任务中执行，也就是在下个宏任务之前被执行。这也就是为什么会按照 `1 2 3` 的顺序执行。

如果不落定状态就去尝试 `await` 一个 Promise 的话，可能导致后续宏任务（包括当前任务队列）无法执行。

```js
const p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    console.log(2);
  }, 200);
});
const p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    console.log(1);
  }, 100);
});
await p1;
await p2;
setTimeout(console.log, 0, "3");
console.log(4);
// 1
// 2
```

### 实例化已解决的期约

通过调用 `Promise.resolve()` 静态方法，可以实例化一个解决的期约。使用这个静态方法，实际上可以把任何值都转换为一个期约。

这个方法是幂等的，如果传入一个 Promise，他的行为就会类似于一个空包装。这个幂等性会保留传入状态。

这个静态方法能够包装任何值，甚至包括错误对象，并将其转化为解决的 Promise。

